# Generated by Django 4.2.10 on 2024-02-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='board',
        ),
        migrations.AddField(
            model_name='projectboard',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_board.team'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks_list', to='base_board.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_board.user'),
        ),
    ]
