# Generated by Django 4.2.10 on 2024-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_board', '0002_remove_task_board_projectboard_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
